title: python4sas
logo: /assets/img/logo.png
description: Python + Pandas for SAS programmers
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - risk.md
  - index.md
